# Generated by Django 3.2.12 on 2023-03-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
    ]
