# Generated by Django 3.2.12 on 2023-03-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_rename_data_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.CharField(max_length=20),
        ),
    ]
